### ISSUE TITLE
Transfer Repo Ownership

### ISSUE THREAD

**Issue by mikelococo** [mikelococo/tt-rss#3]
Per #2 it sounds like you're no longer interested in maintaining this cookbook and you'd like to hand it off to me. I'm happy to take over maintainership. Would you mind doing an official github repository transfer to my account so that existing links and git-clones will continue to work, and also to eliminate confusion of anyone stumbling on your old/out-of-date but formerly authoritative repository?

I've never done it personally, but instructions for transfer are here, it looks pretty simple:
https://help.github.com/articles/how-to-transfer-a-repository

**Comment by wtreur** [comment]
I tried to transfer yesterday, but was unsuccessful, because your fork was in the way. It looks like you removed it, so I let's try it again.

**Comment by wtreur** [comment]
I have send you the transfer request, but I wonder what will happen to the other forks once the original is transferred

**Comment by mikelococo** [comment]
I wasn't watching my email closely enough this weekend, and the transfer request has expired. Can we try one more time? Apologies.

My impression from reading the docs is that forks, clones, and web links all continue to function after the transfer.

**Comment by wtreur** [comment]
No worries. Offline weekend are mostly the best :) I've resend the transfer request.

**Comment by mikelococo** [comment]
Transfer complete. Thanks for your work in getting this cookbook started, and your willingness to pass on the torch now. The fork network appears to have remained intact. I'll get a note in the readme in the next few days to encourage folks to update their clones and links.

**Comment by wtreur** [comment]
Sure thing! Thank you for your commitment and good luck with any further development!

**Comment by dvberkel** [comment]
:+1:
